#!/bin/bash
### BEGIN INIT INFO
# Provides:          liferay
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Launch liferay server
# Description:
### END INIT INFO
#
# Author : Julien Bonjean <julien.bonjean@savoirfairelinux.com>
# Modified by: Dmitri Carpov <dmtiri.carpov@savoirfairelinux.com>
# Modified by: Sven Werlen <sven.werlen@savoirfairelinux.com>

PORTAL_DIR=/opt/liferay-portal
TOMCAT_DIR=$PORTAL_DIR/tomcat
LIFERAY_USER=vagrant

export JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"

# Check the server is still installed
[ -x $PORTAL_DIR ] || exit 0
[ -x $TOMCAT_DIR ] || exit 0

# Get LSB functions
. /lib/lsb/init-functions

case "$1" in
	start)
		logger "Starting liferay..."
		pgrep -u $LIFERAY_USER -f $TOMCAT_DIR > /dev/null 2>&1
		if [ $? -eq 0 ]; then
			log_warning_msg "Liferay is already running"
		exit 1
		fi
		if [ "$USER" = "$LIFERAY_USER" ]; then
			$TOMCAT_DIR/bin/startup.sh > /dev/null 2>&1
		else
			su $LIFERAY_USER -c $TOMCAT_DIR/bin/startup.sh > /dev/null 2>&1
		fi
		sleep 10
		pgrep -u $LIFERAY_USER -f $TOMCAT_DIR > /dev/null 2>&1
		if [ $? -eq 0 ]; then
			exit 0
		fi
			exit 1
		 ;;
	stop)
		logger "Stopping liferay..."
		pgrep -u $LIFERAY_USER -f $TOMCAT_DIR > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			log_warning_msg "Liferay is not running"
			exit 1
		fi
		if [ "$USER" = "$LIFERAY_USER" ]; then
			$TOMCAT_DIR/bin/shutdown.sh > /dev/null 2>&1
		else
			su $LIFERAY_USER -c $TOMCAT_DIR/bin/shutdown.sh > /dev/null 2>&1
		fi
		sleep 3
		pgrep -u $LIFERAY_USER -f $TOMCAT_DIR > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			exit 0
		fi
		log_warning_msg "Not stopped, try to kill gently"
		pkill -f $TOMCAT_DIR
		sleep 3
		pgrep -u $LIFERAY_USER -f $TOMCAT_DIR > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			exit 0
		fi
		log_warning_msg "Still not stopped, kill hardly"
		pkill -9 -u $LIFERAY_USER -f $TOMCAT_DIR
		sleep 1
		pgrep -u $LIFERAY_USER -f $TOMCAT_DIR > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			exit 0
		fi
		log_failure_msg "Error : Cannot stop server!"
		exit 1
		 ;;
	restart|force-reload)
		$SELF stop;
		$SELF start;
		exit 0
		 ;;
	status)
		pgrep -u $LIFERAY_USER -f $TOMCAT_DIR > /dev/null 2>&1
		if [ $? -eq 0 ]; then
			log_success_msg "Liferay is running."
			exit 0
		else
			log_failure_msg "Liferay is not running."
			exit 1
		fi
		 ;;
	*)
		echo "Usage: /etc/init.d/liferay {start|stop|restart|status}"
		exit 1
		 ;;
		esac
	
exit 0
